name: lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change directory
        run: cd nuxt
      - name: Install modules
        run: yarn install
      - name: Run ESLint
        run: yarn lint:style
